// Code generated by go-swagger; DO NOT EDIT.

// Package restapi wash-payment
//
//	Payment system service for self-service car washes
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
