swagger: "2.0"
info:
  description: "Payment system service for self-service car washes"
  title: wash-payment
  version: 1.1.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
securityDefinitions:
  authKey:
    description: Session token inside Authorization header.
    type: apiKey
    in: header
    name: Authorization

paths:
  /healthCheck:
    get:
      tags:
        - Standard
      operationId: healthCheck
      summary: Health check
      description: Checking the server health status.
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              ok:
                type: boolean
  
  /organizations:
    get:
      tags:
        - Organizations
      operationId: list
      summary: Get organizations
      description: Get a list of organizations
      security:
        - authKey: []
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
          minimum: 1
        - name: pageSize
          in: query
          type: integer
          default: 10
          maximum: 100
          minimum: 1
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/OrganizationPage"
        403: {$ref: '#/responses/Forbidden'}
        default: {$ref: '#/responses/InternalError'}

  /organizations/{id}:
    get:
      tags:
        - Organizations
      operationId: get
      summary: Get organization
      description: Get information about the specified organization
      security:
        - authKey: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Organization"
        403: {$ref: '#/responses/Forbidden'}
        404: {$ref: '#/responses/NotFound'}
        default: {$ref: '#/responses/InternalError'}

  /organizations/{id}/deposit:
    post:
      tags:
        - Organizations
      operationId: deposit
      summary: Top up balance
      description: Increase the balance of the specified organization by the specified number of kopecks
      security:
        - authKey: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Deposit"
      responses:
        204:
          description: OK
        400: {$ref: '#/responses/BadRequest'}
        403: {$ref: '#/responses/Forbidden'}
        404: {$ref: '#/responses/NotFound'}
        default: {$ref: '#/responses/InternalError'}
  
  /organizations/{id}/service-prices:
    put:
      tags:
        - Organizations
      operationId: setServicePrices
      summary: Set service prices
      description: Set prices for services for the specified organization
      security:
        - authKey: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ServicePrices"
      responses:
        204:
          description: OK
        400: {$ref: '#/responses/BadRequest'}
        403: {$ref: '#/responses/Forbidden'}
        404: {$ref: '#/responses/NotFound'}
        default: {$ref: '#/responses/InternalError'}


  /organizations/{id}/transactions:
    get:
      tags:
        - Organizations
      operationId: transactions
      summary: Get organization transactions
      description: Get a list of transactions for the specified organization
      security:
        - authKey: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - name: page
          in: query
          type: integer
          default: 1
          minimum: 1
        - name: pageSize
          in: query
          type: integer
          default: 10
          maximum: 100
          minimum: 1
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/TransactionPage"
        403: {$ref: '#/responses/Forbidden'}
        404: {$ref: '#/responses/NotFound'}
        default: {$ref: '#/responses/InternalError'}

responses:
  BadRequest:
    description: Bad request
    schema:
      $ref: "#/definitions/Error"
  Forbidden:
    description: Forbidden
    schema:
      $ref: "#/definitions/Error"
  NotFound:
    description: Not found
    schema:
      $ref: "#/definitions/Error"
  InternalError:
    description: Internal error
    schema:
      $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code OR >= 600
        type: integer
        format: int32
      message:
        type: string

  Service:
    description: Service, for the use of which the payment was made
    type: string
    enum: ["payment", "bonus", "sbp"]
  
  Operation:
    description: Type of operation
    type: string
    enum: ["deposit", "debit"]

  Deposit:
    type: object
    properties:
      amount:
        description: Amount in kopecks (RUB * 10^2)
        type: integer
        format: int64
        minimum: 1
    required:
      - amount
  
  ServicePrices:
    type: object
    description: Prices for services for a specific organization in kopecks (RUB * 10^2)
    properties:
      bonus:
        type: integer
        format: int64
        minimum: 0
      sbp:
        type: integer
        format: int64
        minimum: 0
    required:
      - bonus
      - sbp

  Organization:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      displayName:
        type: string
      description:
        type: string
      balance:
        description: Balance in kopecks (RUB * 10^2)
        type: integer
        format: int64
        minimum: 0
      servicePrices:
        $ref: "#/definitions/ServicePrices"
    required:
      - id
      - name
      - displayName
      - description
      - balance
      - servicePrices
  
  OrganizationPage:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Organization"
      page:
        type: integer
      pageSize:
        type: integer
      totalPages:
        type: integer
      totalItems:
        type: integer
    required:
      - items
      - page
      - pageSize
      - totalPages
      - totalItems

  Transaction:
    type: object
    properties:
      id:
        type: string
        format: uuid
      organizationId:
        type: string
        format: uuid
      groupId:
        description: Group that requested payment for using the service
        x-nullable: true
        type: string
        format: uuid
      stations–°ount:
        description: Number of stations in the car wash that requested payment for using of the service
        x-nullable: true
        type: integer
        minimum: 1
      userId:
        description: The user who credited the organisation's account
        x-nullable: true
        type: string
      createdAt:
        type: string
        format: date-time
      forDate:
        x-nullable: true
        type: string
        format: date
      operation:
        $ref: '#/definitions/Operation'
      sevice:
        $ref: '#/definitions/Service'
      amount:
        description: Amount in kopecks (RUB * 10^2)
        type: integer
        format: int64
        minimum: 1
    required:
      - id
      - organizationId
      - createdAt
      - operation
      - sevice
      - amount
  
  TransactionPage:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Transaction"
      page:
        type: integer
      pageSize:
        type: integer
      totalPages:
        type: integer
      totalItems:
        type: integer
    required:
      - items
      - page
      - pageSize
      - totalPages
      - totalItems
