// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"wash-payment/internal/pkg/openapi/models"
)

// GetOKCode is the HTTP code returned for type GetOK
const GetOKCode int = 200

/*
GetOK OK

swagger:response getOK
*/
type GetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Organization `json:"body,omitempty"`
}

// NewGetOK creates GetOK with default headers values
func NewGetOK() *GetOK {

	return &GetOK{}
}

// WithPayload adds the payload to the get o k response
func (o *GetOK) WithPayload(payload *models.Organization) *GetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get o k response
func (o *GetOK) SetPayload(payload *models.Organization) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetOK) GetResponder() {}

// GetForbiddenCode is the HTTP code returned for type GetForbidden
const GetForbiddenCode int = 403

/*
GetForbidden Forbidden

swagger:response getForbidden
*/
type GetForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetForbidden creates GetForbidden with default headers values
func NewGetForbidden() *GetForbidden {

	return &GetForbidden{}
}

// WithPayload adds the payload to the get forbidden response
func (o *GetForbidden) WithPayload(payload *models.Error) *GetForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get forbidden response
func (o *GetForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetForbidden) GetResponder() {}

// GetNotFoundCode is the HTTP code returned for type GetNotFound
const GetNotFoundCode int = 404

/*
GetNotFound Not found

swagger:response getNotFound
*/
type GetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNotFound creates GetNotFound with default headers values
func NewGetNotFound() *GetNotFound {

	return &GetNotFound{}
}

// WithPayload adds the payload to the get not found response
func (o *GetNotFound) WithPayload(payload *models.Error) *GetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get not found response
func (o *GetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetNotFound) GetResponder() {}

/*
GetDefault Internal error

swagger:response getDefault
*/
type GetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDefault creates GetDefault with default headers values
func NewGetDefault(code int) *GetDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get default response
func (o *GetDefault) WithStatusCode(code int) *GetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get default response
func (o *GetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get default response
func (o *GetDefault) WithPayload(payload *models.Error) *GetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get default response
func (o *GetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetDefault) GetResponder() {}

type GetNotImplementedResponder struct {
	middleware.Responder
}

func (*GetNotImplementedResponder) GetResponder() {}

func GetNotImplemented() GetResponder {
	return &GetNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Get has not yet been implemented",
		),
	}
}

type GetResponder interface {
	middleware.Responder
	GetResponder()
}
