// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"wash-payment/internal/pkg/openapi/models"
)

// SetServicePricesNoContentCode is the HTTP code returned for type SetServicePricesNoContent
const SetServicePricesNoContentCode int = 204

/*
SetServicePricesNoContent OK

swagger:response setServicePricesNoContent
*/
type SetServicePricesNoContent struct {
}

// NewSetServicePricesNoContent creates SetServicePricesNoContent with default headers values
func NewSetServicePricesNoContent() *SetServicePricesNoContent {

	return &SetServicePricesNoContent{}
}

// WriteResponse to the client
func (o *SetServicePricesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *SetServicePricesNoContent) SetServicePricesResponder() {}

// SetServicePricesBadRequestCode is the HTTP code returned for type SetServicePricesBadRequest
const SetServicePricesBadRequestCode int = 400

/*
SetServicePricesBadRequest Bad request

swagger:response setServicePricesBadRequest
*/
type SetServicePricesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetServicePricesBadRequest creates SetServicePricesBadRequest with default headers values
func NewSetServicePricesBadRequest() *SetServicePricesBadRequest {

	return &SetServicePricesBadRequest{}
}

// WithPayload adds the payload to the set service prices bad request response
func (o *SetServicePricesBadRequest) WithPayload(payload *models.Error) *SetServicePricesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set service prices bad request response
func (o *SetServicePricesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetServicePricesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *SetServicePricesBadRequest) SetServicePricesResponder() {}

// SetServicePricesForbiddenCode is the HTTP code returned for type SetServicePricesForbidden
const SetServicePricesForbiddenCode int = 403

/*
SetServicePricesForbidden Forbidden

swagger:response setServicePricesForbidden
*/
type SetServicePricesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetServicePricesForbidden creates SetServicePricesForbidden with default headers values
func NewSetServicePricesForbidden() *SetServicePricesForbidden {

	return &SetServicePricesForbidden{}
}

// WithPayload adds the payload to the set service prices forbidden response
func (o *SetServicePricesForbidden) WithPayload(payload *models.Error) *SetServicePricesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set service prices forbidden response
func (o *SetServicePricesForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetServicePricesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *SetServicePricesForbidden) SetServicePricesResponder() {}

// SetServicePricesNotFoundCode is the HTTP code returned for type SetServicePricesNotFound
const SetServicePricesNotFoundCode int = 404

/*
SetServicePricesNotFound Not found

swagger:response setServicePricesNotFound
*/
type SetServicePricesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetServicePricesNotFound creates SetServicePricesNotFound with default headers values
func NewSetServicePricesNotFound() *SetServicePricesNotFound {

	return &SetServicePricesNotFound{}
}

// WithPayload adds the payload to the set service prices not found response
func (o *SetServicePricesNotFound) WithPayload(payload *models.Error) *SetServicePricesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set service prices not found response
func (o *SetServicePricesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetServicePricesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *SetServicePricesNotFound) SetServicePricesResponder() {}

/*
SetServicePricesDefault Internal error

swagger:response setServicePricesDefault
*/
type SetServicePricesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetServicePricesDefault creates SetServicePricesDefault with default headers values
func NewSetServicePricesDefault(code int) *SetServicePricesDefault {
	if code <= 0 {
		code = 500
	}

	return &SetServicePricesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set service prices default response
func (o *SetServicePricesDefault) WithStatusCode(code int) *SetServicePricesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set service prices default response
func (o *SetServicePricesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set service prices default response
func (o *SetServicePricesDefault) WithPayload(payload *models.Error) *SetServicePricesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set service prices default response
func (o *SetServicePricesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetServicePricesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *SetServicePricesDefault) SetServicePricesResponder() {}

type SetServicePricesNotImplementedResponder struct {
	middleware.Responder
}

func (*SetServicePricesNotImplementedResponder) SetServicePricesResponder() {}

func SetServicePricesNotImplemented() SetServicePricesResponder {
	return &SetServicePricesNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.SetServicePrices has not yet been implemented",
		),
	}
}

type SetServicePricesResponder interface {
	middleware.Responder
	SetServicePricesResponder()
}
