// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewTransactionsParams creates a new TransactionsParams object
// with the default values initialized.
func NewTransactionsParams() TransactionsParams {

	var (
		// initialize parameters with default values

		pageDefault     = int64(1)
		pageSizeDefault = int64(10)
	)

	return TransactionsParams{
		Page: &pageDefault,

		PageSize: &pageSizeDefault,
	}
}

// TransactionsParams contains all the bound params for the transactions operation
// typically these are obtained from a http.Request
//
// swagger:parameters transactions
type TransactionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	GroupID *strfmt.UUID
	/*
	  Required: true
	  In: path
	*/
	ID strfmt.UUID
	/*
	  In: query
	*/
	Operation *string
	/*
	  Minimum: 1
	  In: query
	  Default: 1
	*/
	Page *int64
	/*
	  Maximum: 100
	  Minimum: 1
	  In: query
	  Default: 10
	*/
	PageSize *int64
	/*
	  In: query
	*/
	Service *string
	/*
	  In: query
	*/
	WashServerID *strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTransactionsParams() beforehand.
func (o *TransactionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qGroupID, qhkGroupID, _ := qs.GetOK("groupId")
	if err := o.bindGroupID(qGroupID, qhkGroupID, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qOperation, qhkOperation, _ := qs.GetOK("operation")
	if err := o.bindOperation(qOperation, qhkOperation, route.Formats); err != nil {
		res = append(res, err)
	}

	qPage, qhkPage, _ := qs.GetOK("page")
	if err := o.bindPage(qPage, qhkPage, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageSize, qhkPageSize, _ := qs.GetOK("pageSize")
	if err := o.bindPageSize(qPageSize, qhkPageSize, route.Formats); err != nil {
		res = append(res, err)
	}

	qService, qhkService, _ := qs.GetOK("service")
	if err := o.bindService(qService, qhkService, route.Formats); err != nil {
		res = append(res, err)
	}

	qWashServerID, qhkWashServerID, _ := qs.GetOK("washServerId")
	if err := o.bindWashServerID(qWashServerID, qhkWashServerID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGroupID binds and validates parameter GroupID from query.
func (o *TransactionsParams) bindGroupID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("groupId", "query", "strfmt.UUID", raw)
	}
	o.GroupID = (value.(*strfmt.UUID))

	if err := o.validateGroupID(formats); err != nil {
		return err
	}

	return nil
}

// validateGroupID carries on validations for parameter GroupID
func (o *TransactionsParams) validateGroupID(formats strfmt.Registry) error {

	if err := validate.FormatOf("groupId", "query", "uuid", o.GroupID.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *TransactionsParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("id", "path", "strfmt.UUID", raw)
	}
	o.ID = *(value.(*strfmt.UUID))

	if err := o.validateID(formats); err != nil {
		return err
	}

	return nil
}

// validateID carries on validations for parameter ID
func (o *TransactionsParams) validateID(formats strfmt.Registry) error {

	if err := validate.FormatOf("id", "path", "uuid", o.ID.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindOperation binds and validates parameter Operation from query.
func (o *TransactionsParams) bindOperation(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Operation = &raw

	if err := o.validateOperation(formats); err != nil {
		return err
	}

	return nil
}

// validateOperation carries on validations for parameter Operation
func (o *TransactionsParams) validateOperation(formats strfmt.Registry) error {

	if err := validate.EnumCase("operation", "query", *o.Operation, []interface{}{"deposit", "debit"}, true); err != nil {
		return err
	}

	return nil
}

// bindPage binds and validates parameter Page from query.
func (o *TransactionsParams) bindPage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewTransactionsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("page", "query", "int64", raw)
	}
	o.Page = &value

	if err := o.validatePage(formats); err != nil {
		return err
	}

	return nil
}

// validatePage carries on validations for parameter Page
func (o *TransactionsParams) validatePage(formats strfmt.Registry) error {

	if err := validate.MinimumInt("page", "query", *o.Page, 1, false); err != nil {
		return err
	}

	return nil
}

// bindPageSize binds and validates parameter PageSize from query.
func (o *TransactionsParams) bindPageSize(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewTransactionsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("pageSize", "query", "int64", raw)
	}
	o.PageSize = &value

	if err := o.validatePageSize(formats); err != nil {
		return err
	}

	return nil
}

// validatePageSize carries on validations for parameter PageSize
func (o *TransactionsParams) validatePageSize(formats strfmt.Registry) error {

	if err := validate.MinimumInt("pageSize", "query", *o.PageSize, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("pageSize", "query", *o.PageSize, 100, false); err != nil {
		return err
	}

	return nil
}

// bindService binds and validates parameter Service from query.
func (o *TransactionsParams) bindService(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Service = &raw

	if err := o.validateService(formats); err != nil {
		return err
	}

	return nil
}

// validateService carries on validations for parameter Service
func (o *TransactionsParams) validateService(formats strfmt.Registry) error {

	if err := validate.EnumCase("service", "query", *o.Service, []interface{}{"payment", "bonus", "sbp"}, true); err != nil {
		return err
	}

	return nil
}

// bindWashServerID binds and validates parameter WashServerID from query.
func (o *TransactionsParams) bindWashServerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("washServerId", "query", "strfmt.UUID", raw)
	}
	o.WashServerID = (value.(*strfmt.UUID))

	if err := o.validateWashServerID(formats); err != nil {
		return err
	}

	return nil
}

// validateWashServerID carries on validations for parameter WashServerID
func (o *TransactionsParams) validateWashServerID(formats strfmt.Registry) error {

	if err := validate.FormatOf("washServerId", "query", "uuid", o.WashServerID.String(), formats); err != nil {
		return err
	}
	return nil
}
